# Generated by Django 2.1.2 on 2019-01-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
