# Generated by Django 2.1.2 on 2019-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190105_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/img/extra.png', null=True, upload_to='img/users'),
        ),
    ]
